# Generated by Django 5.2 on 2025-04-22 19:11

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('address', models.TextField(blank=True, max_length=25)),
                ('phonenumber', models.CharField(blank=True, max_length=25)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('amount_received', models.FloatField(blank=True, default=0, null=True)),
                ('branch', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.category')),
                ('salesagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('amount_due', models.PositiveIntegerField()),
                ('due_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_of_dispatch', models.DateField(auto_now_add=True)),
                ('sales_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=10, null=True)),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('type_of_stock', models.CharField(max_length=20)),
                ('cost', models.FloatField(blank=True)),
                ('supplier_type', models.CharField(choices=[('individual', 'Individual Dealer'), ('company', 'Company'), ('farm', 'KGL Farm')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('branch', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20)),
                ('unit_price', models.FloatField(blank=True, default=0, null=True)),
                ('unit_cost', models.FloatField(blank=True, default=0, null=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.category')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.stock'),
        ),
    ]
