# Generated by Django 5.2 on 2025-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_rename_time_sale_dispatch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
