# Generated by Django 5.2 on 2025-05-03 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_stock_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='national_id',
            field=models.CharField(blank=True, help_text='Enter a valid NIN (e.g., CM123456789012)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid NIN (e.g., CM123456789012)', regex='^[A-Z]{2}[0-9A-Z]{12}$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('cheque', 'Cheque')], default='Cash', max_length=10),
        ),
    ]
